{
    "Target": {
        "EntitySet": "RM_Risks",
        "Service": "/risksmobile/Services/RiskManagementAppService.service",
        "ReadLink": "{@odata.readLink}"
    },
    "OnSuccess": "/risksmobile/Actions/DeleteEntitySuccessMessage.action",
    "OnFailure": "/risksmobile/Actions/DeleteEntityFailureMessage.action",
    "ActionResult": {
        "_Name": "delete"
    },
    "_Type": "Action.Type.ODataService.DeleteEntity"
}