{
    "_Type": "Action.Type.ODataService.DraftEnabled.Discard",
    "Target": {
        "Service": "/risksmobile/Services/RiskManagementAppService.service",
        "EntitySet": "RM_Mitigations",
        "ReadLink": "{@odata.readLink}"
    },
    "ShowActivityIndicator": true,
    "ActionResult": {
        "_Name": "update"
    },
    "OnSuccess": {
        "Name": "/risksmobile/Actions/UpdateEntitySuccessMessage.action",
        "Properties": {
            "Message": "Draft Discarded"
        }
    },
    "OnFailure": "/risksmobile/Actions/UpdateEntityFailureMessage.action"
}