{
    "ModalPageFullscreen": false,
    "ModalPage": true,
    "PageToOpen": "/risksmobile/Pages/RiskManagementAppService_RM_Mitigations/RM_Mitigations_CreateRM_Risks.page",
    "_Type": "Action.Type.Navigation"
}