{
    "CreateLinks": [],
    "OnFailure": "/risksmobile/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/risksmobile/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "createdAt": "#Control:createdAt/#Value",
        "createdBy": "#Control:createdBy/#Value",
        "description": "#Control:description/#Value",
        "owner": "#Control:owner/#Value",
        "timeline": "#Control:timeline/#Value"
    },
    "Target": {
        "EntitySet": "RM_Mitigations",
        "Service": "/risksmobile/Services/RiskManagementAppService.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}